groups:
- name: ika_validator_alerts
  rules:

  - alert: IkaNoLeaderRoundProgress
    expr: increase(consensus_last_committed_leader_round{network="testnet",group="IkaValidator"}[10m]) == 0
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "consensus_last_committed_leader_round has been stuck for 10m"
      description: "The metric `consensus_last_committed_leader_round` has not increased in the last 10 minutes."

  - alert: IkaNoSyncFetchedIndexProgress
    expr: increase(consensus_commit_sync_fetched_index{network="testnet",group="IkaValidator"}[10m]) == 0
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: "consensus_commit_sync_fetched_index has been stuck for 10m"
      description: "The metric `consensus_commit_sync_fetched_index` has not increased in the last 10 minutes."
    
  - alert: IkaNodeDown
    expr: up{job="Ika-Validator"} == 0
    for: 10m
    labels:
      severity: critical
    annotations:
      summary: "Ika node is down"
      description: "The Ika validator target is not reachable (up == 0) for over 10 minutes."