{
 "title": "Ika Development",
 "description": "Iota validator dashboard",
 "tags": [
  "testnet",
  "mainnet",
  "rpc"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(uptime{group=~\"IkaValidator|Fullnode\"},network)"
    }
   },
   { "name": "authority", "label": "Authority", "query": "TrustedPoint" }
  ]
 },
 "panels": [
  {
   "title": "IKA Node - General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consensus Round Sync",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_last_committed_leader_round{network=\"$network\", group=\"IkaValidator\"} / consensus_highest_accepted_round{network=\"$network\", group=\"IkaValidator\"} * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Epoch",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "current_epoch{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Consensus Missing Blocks",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_block_manager_missing_blocks{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "${authority} Consensus Reputation Score",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_reputation_scores{network=\"$network\", group=\"IkaValidator\", authority=\"$authority\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Last Decided Round",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_last_decided_leader_round {network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Last Commit Index",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_last_commit_index{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Proposed Blocks Size [1m avg]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\r\n  rate(consensus_proposed_block_size_sum{network=\"$network\", group=\"IkaValidator\"}[1m])\r\n)\r\n/\r\nsum(\r\n  rate(consensus_proposed_block_size_count{network=\"$network\", group=\"IkaValidator\"}[1m])\r\n)\r\n",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Total Peers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ika_quinn_network_peers{network=\"$network\", group=\"IkaValidator\"} + consensus__quinn_network_peers {network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "AVG Cons Reputation Score (All Vals)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(\r\n  consensus_reputation_scores{\r\n    network=\"$network\",\r\n    group=\"IkaValidator\"\r\n  }\r\n)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Last Committed Round",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_last_committed_leader_round{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Max Commit Index",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_commit_sync_fetched_index{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Proposed Blocks (/s) [1m avg]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(consensus_proposed_blocks{network=\"$network\", group=\"IkaValidator\", force=\"false\"}[5m])) + sum(rate(consensus_proposed_blocks{network=\"$network\", group=\"IkaValidator\", force=\"true\"}[5m]))",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Node Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "uptime{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(uptime{network=\"$network\", group=\"IkaValidator\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Low Scoring Nodes",
     "type": "stat",
     "description": "s Number of low scoring authorities based on reputation scores from consensus",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_handler_num_low_scoring_authorities{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Committed Msgs (/s) [1m avg]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(consensus_committed_messages{network=\"$network\", group=\"IkaValidator\", authority=\"$authority\"}[1m])",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Round Sync Lag",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_highest_accepted_round{network=\"$network\", group=\"IkaValidator\"} - consensus_last_committed_leader_round{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Commit Sync Lag",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_last_commit_index{network=\"$network\", group=\"IkaValidator\"} - consensus_commit_sync_fetched_index{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "TXs (/s) [1m avg]",
     "type": "stat",
     "description": "Total number of transaction certificates handled per second",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(total_transaction_certificates{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "type": "status-history",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "(\r\n  scalar(\r\n    max(\r\n      consensus_last_committed_authority_round{\r\n        network=\"$network\",\r\n        group=\"IkaValidator\",\r\n      }\r\n    )\r\n  )\r\n)\r\n-\r\nconsensus_last_committed_authority_round{\r\n  network=\"$network\",\r\n  group=\"IkaValidator\",\r\n  authority=\"$authority\"\r\n}",
       "legendFormat": "- Round Lag 🐢"
      },
      {
       "expr": "rate(consensus_last_committed_authority_round{network=\"$network\", group=\"IkaValidator\", authority=\"$authority\"}[5m])",
       "legendFormat": "- Commit Rate🚀"
      },
      {
       "expr": "avg_over_time(consensus_reputation_scores{network=\"$network\", group=\"IkaValidator\", authority=\"$authority\"}[5m])",
       "legendFormat": "- Avg Reputation 🌟"
      },
      {
       "expr": "sum(rate(consensus_proposed_blocks{network=\"$network\", group=\"IkaValidator\", force=\"false\"}[5m])) + sum(rate(consensus_proposed_blocks{network=\"$network\", group=\"IkaValidator\", force=\"true\"}[5m]))",
       "legendFormat": "- Proposals/s 🧱"
      },
      {
       "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(consensus_block_commit_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "- Commit Lat (p95) ⏳"
      },
      {
       "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(consensus_quorum_receive_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "- Quorum Lat p95 ⏱️ "
      },
      {
       "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(authority_state_commit_certificate_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "- Cert Lat (p95) 🟪"
      },
      {
       "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le) (\r\n    rate(authority_state_commit_certificate_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "- Cert Lat (p50) 🟨"
      }
     ]
    }
   ]
  },
  {
   "title": "IKA Node - Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "rate(num_shared_obj_tx{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "Shared"
      },
      {
       "expr": "rate(total_transaction_certificates{network=\"$network\", group=\"IkaValidator\"}[1m]) - rate(num_shared_obj_tx{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "Owned"
      },
      {
       "expr": "rate(total_transaction_certificates{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Rounds",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 62 },
     "targets": [
      {
       "expr": "consensus_last_committed_leader_round{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "Last Committed"
      },
      {
       "expr": "consensus_highest_accepted_round{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "Highest Accepted"
      },
      {
       "expr": "consensus_last_decided_leader_round{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "Last Decided"
      },
      {
       "expr": "consensus_threshold_clock_round{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "Threshold Clock"
      }
     ]
    },
    {
     "title": "Rounds per Second [1m avg]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
     "targets": [
      {
       "expr": "rate(consensus_last_committed_leader_round{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "Last Committed"
      },
      {
       "expr": "rate(consensus_highest_accepted_round{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "Highest Accepted"
      },
      {
       "expr": "rate(consensus_last_decided_leader_round{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "Last Decided"
      },
      {
       "expr": "rate(consensus_threshold_clock_round{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "Threshold Clock"
      }
     ]
    },
    {
     "title": "Peers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ika_quinn_network_peers{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "network"
      },
      {
       "expr": "consensus__quinn_network_peers {network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "consensus"
      },
      {
       "expr": "sum(consensus_subscribed_by{network=\"$network\", group=\"IkaValidator\"})",
       "legendFormat": "block stream - subscribers"
      },
      {
       "expr": "sum(consensus_subscribed_to{network=\"$network\", group=\"IkaValidator\"})",
       "legendFormat": "block stream - subscriptions"
      }
     ]
    },
    {
     "title": "Commits",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 71 },
     "targets": [
      {
       "expr": "consensus_commit_sync_fetched_index{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "Max Commit"
      },
      {
       "expr": "consensus_last_commit_index{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "Last Commit"
      },
      {
       "expr": "consensus_commit_sync_local_index{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "Max Local"
      },
      {
       "expr": "consensus_commit_sync_quorum_index{network=\"$network\", group=\"IkaValidator\"}",
       "legendFormat": "Max Voted"
      }
     ]
    },
    {
     "title": "Commits per Second [1m avg]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 71 },
     "targets": [
      {
       "expr": "rate(consensus_commit_sync_fetched_index{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "Max Commit"
      },
      {
       "expr": "rate(consensus_last_commit_index{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "Last Commit"
      },
      {
       "expr": "rate(consensus_commit_sync_local_index{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "Max Local"
      },
      {
       "expr": "rate(consensus_commit_sync_quorum_index{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "Max Voted"
      }
     ]
    },
    {
     "title": "Ika Requests (/s) by Route [1 m avg]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "rate(ika_inbound_requests{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "inbound - {{route}}"
      },
      {
       "expr": "rate(ika_outbound_requests{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "outbound - {{route}}"
      }
     ]
    },
    {
     "title": "Avg Spans Latency",
     "type": "timeseries",
     "description": "Displays the average latency for spans in the fullnode service.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(tracing_span_latencies_sum{group=\"IkaValidator\", network=\"$network\"} / tracing_span_latencies_count{group=\"IkaValidator\", network=\"$network\"}) / 1e9",
       "legendFormat": "{{span_name}}"
      }
     ]
    },
    {
     "title": "Avg Ika Requests Latency by Route",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "1000 * (ika_outbound_request_latency_sum{group=\"IkaValidator\", network=\"$network\"} / ika_outbound_request_latency_count{group=\"IkaValidator\", network=\"$network\"})",
       "legendFormat": "outbound - {{route}}"
      },
      {
       "expr": "1000 * (ika_inbound_request_latency_sum{group=\"IkaValidator\", network=\"$network\"} / ika_inbound_request_latency_count{group=\"IkaValidator\", network=\"$network\"})",
       "legendFormat": "inbound - {{route}}"
      }
     ]
    },
    {
     "title": "DB Pruning",
     "type": "timeseries",
     "description": "The last epoch for which the consensus store was pruned",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "avg_over_time(last_pruned_consensus_db_epoch{network=\"$network\", group=\"IkaValidator\"}[24h])",
       "legendFormat": "Last Pruned Checkpoint"
      }
     ]
    }
   ]
  },
  {
   "title": "IKA Node - Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consensus Accepted Blocks per Second [1m avg]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 565 },
     "targets": [
      {
       "expr": "rate(consensus_accepted_blocks{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "source - {{source}}"
      }
     ]
    },
    {
     "title": "Consensus Proposed Block Rate per Second [1m avg]",
     "type": "timeseries",
     "description": "Total number of proposed blocks. If force is true then this block has been created forcefully via a leader timeout event.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 565 },
     "targets": [
      {
       "expr": "rate(consensus_proposed_blocks{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "force - {{force}}"
      }
     ]
    },
    {
     "title": "Consensus Leader Timeouts per Second [1m avg]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 565 },
     "targets": [
      {
       "expr": "rate(consensus_leader_timeout_total{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "timeout_type - {{timeout_type}}"
      }
     ]
    },
    {
     "title": "Quorum Receive Latency Sum [1m avg]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 713 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(\r\n  rate(consensus_quorum_receive_latency_sum{network=\"$network\", group=\"IkaValidator\"}[1m])\r\n)\r\n/\r\nsum(\r\n  rate(consensus_quorum_receive_latency_count{network=\"$network\", group=\"IkaValidator\"}[1m])\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consensus Request Latency (p95) by Route",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 713 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (route, le) (\r\n    rate(consensus__outbound_request_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "outbound - {{route}}"
      },
      {
       "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (route, le) (\r\n    rate(consensus__inbound_request_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "inbound - {{route}}"
      }
     ]
    },
    {
     "title": "Consensus Requests per Second by Route [1 m avg]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 713 },
     "targets": [
      {
       "expr": "rate(consensus__outbound_requests{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "inbound - {{route}}"
      },
      {
       "expr": "rate(consensus__inbound_requests{network=\"$network\", group=\"IkaValidator\"}[1m])",
       "legendFormat": "outbound - {{route}}"
      }
     ]
    },
    {
     "title": "Consensus Proposal Interval",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 722 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le) (\r\n    rate(consensus_block_proposal_interval_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(consensus_block_proposal_interval_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\r\n  0.75,\r\n  sum by (le) (\r\n    rate(consensus_block_proposal_interval_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le) (\r\n    rate(consensus_block_proposal_interval_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Quorum Receive Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 722 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le) (\r\n    rate(consensus_quorum_receive_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(consensus_quorum_receive_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\r\n  0.75,\r\n  sum by (le) (\r\n    rate(consensus_quorum_receive_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le) (\r\n    rate(consensus_quorum_receive_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Consensus Block Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 722 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (le) (\r\n    rate(consensus_block_commit_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(\r\n  0.75,\r\n  sum by (le) (\r\n    rate(consensus_block_commit_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(consensus_block_commit_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le) (\r\n    rate(consensus_block_commit_latency_bucket{network=\"$network\", group=\"IkaValidator\"}[5m])\r\n  )\r\n)",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "IKA Node - Validators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Committed Consensus Round Lag ",
     "type": "status-history",
     "gridPos": { "h": 31, "w": 12, "x": 0, "y": 566 },
     "targets": [
      {
       "expr": "(\r\n  scalar(\r\n    max(\r\n      consensus_last_committed_authority_round{\r\n        network=\"$network\",\r\n        group=\"IkaValidator\"\r\n      }\r\n    )\r\n  )\r\n)\r\n-\r\nconsensus_last_committed_authority_round{\r\n  network=\"$network\",\r\n  group=\"IkaValidator\"\r\n}",
       "legendFormat": "{{authority}}"
      }
     ]
    },
    {
     "title": "Consensus Round Commit Rate ",
     "type": "status-history",
     "gridPos": { "h": 31, "w": 12, "x": 12, "y": 566 },
     "targets": [
      {
       "expr": "rate(consensus_last_committed_authority_round{network=\"$network\", group=\"IkaValidator\"}[2m])",
       "legendFormat": "{{authority}}"
      }
     ]
    },
    {
     "title": "Consensus Reputation Score [5m avg]",
     "type": "status-history",
     "gridPos": { "h": 31, "w": 12, "x": 0, "y": 643 },
     "targets": [
      {
       "expr": "avg_over_time(consensus_reputation_scores{network=\"$network\", group=\"IkaValidator\"}[5m])",
       "legendFormat": "{{authority}}"
      }
     ]
    },
    {
     "title": "Highest Verified Consensus Round Lag ",
     "type": "status-history",
     "gridPos": { "h": 31, "w": 12, "x": 12, "y": 643 },
     "targets": [
      {
       "expr": "(\r\n  scalar(\r\n    max(\r\n      consensus_highest_verified_authority_round{\r\n        network=\"$network\",\r\n        group=\"IkaValidator\"\r\n      }\r\n    )\r\n  )\r\n)\r\n-\r\nconsensus_highest_verified_authority_round{\r\n  network=\"$network\",\r\n  group=\"IkaValidator\"\r\n}",
       "legendFormat": "{{authority}}"
      }
     ]
    },
    {
     "title": "Missing Blocks by Validator",
     "type": "bargauge",
     "gridPos": { "h": 31, "w": 12, "x": 0, "y": 674 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_block_manager_missing_blocks_by_authority{network=\"$network\",group=\"IkaValidator\"}\r\n",
       "legendFormat": "{{authority}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SUI Node -  General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checkpoints Sync",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 567 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "last_executed_checkpoint{network=\"$network\", group=\"Fullnode\"}/highest_synced_checkpoint{network=\"$network\", group=\"Fullnode\"} * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Safe Mode",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 3, "y": 567 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "is_safe_mode{network=\"$network\", group=\"Fullnode\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Peers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 567 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sui_quinn_network_peers{network=\"$network\", group=\"Fullnode\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Epoch",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 567 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "current_epoch{network=\"$network\", group=\"Fullnode\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Highest Synced Checkpoint",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 567 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(highest_synced_checkpoint{network=\"$network\", group=\"Fullnode\"})",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "RPC Requests (/s) [1m avg]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 567 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\r\n  rate(\r\n    rpc_requests_by_route{network=\"$network\",group=\"Fullnode\"}[1m]\r\n  )\r\n)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Total Transaction Certs",
     "type": "stat",
     "description": "Total number of transaction certificates handled",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 567 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "total_transaction_certificates{network=\"$network\", group=\"Fullnode\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 609 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(uptime{network=\"$network\", group=\"Fullnode\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Checkpoint Execution Backlog",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 609 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "highest_known_checkpoint{network=\"$network\", group=\"Fullnode\"} - last_executed_checkpoint{network=\"$network\", group=\"Fullnode\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Checkpoint Sync Lag",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 609 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_min(highest_synced_checkpoint{network=\"$network\", group=\"Fullnode\"} - highest_known_checkpoint{network=\"$network\", group=\"Fullnode\"}, 0)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Total RPC Requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 609 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rpc_requests_by_route{network=\"$network\", group=\"Fullnode\"})",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Transactions (/s) [1m avg]",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 609 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(total_transaction_certificates{network=\"$network\", group=\"Fullnode\"}[1m])",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Node Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 610 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "uptime{network=\"$network\", group=\"Fullnode\"}",
       "legendFormat": "{{version}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SUI Node - Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "rate(num_shared_obj_tx{network=\"$network\", group=\"Fullnode\"}[1m])",
       "legendFormat": "Shared"
      },
      {
       "expr": "rate(total_transaction_certificates{network=\"$network\", group=\"Fullnode\"}[1m]) - rate(num_shared_obj_tx{network=\"$network\", group=\"Fullnode\"}[1m])",
       "legendFormat": "Owned"
      },
      {
       "expr": "rate(total_transaction_certificates{network=\"$network\", group=\"Fullnode\"}[1m])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Checkpoints Sync",
     "type": "timeseries",
     "description": "last_executed_checkpoint / highest_synced_checkpoint",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "last_executed_checkpoint{network=\"$network\", group=\"Fullnode\"}/highest_synced_checkpoint{network=\"$network\", group=\"Fullnode\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Checkpoints per Second [1m avg]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
     "targets": [
      {
       "expr": "rate(highest_synced_checkpoint{network=\"$network\", group=\"Fullnode\"}[1m])",
       "legendFormat": "Highest Synced"
      },
      {
       "expr": "rate(highest_known_checkpoint{network=\"$network\", group=\"Fullnode\"}[1m])",
       "legendFormat": "Highest Known"
      },
      {
       "expr": "rate(highest_verified_checkpoint{network=\"$network\", group=\"Fullnode\"}[1m])",
       "legendFormat": "Highest Verified"
      },
      {
       "expr": "rate(last_executed_checkpoint{network=\"$network\", group=\"Fullnode\"}[1m])",
       "legendFormat": "Last Executed"
      }
     ]
    },
    {
     "title": "Peers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sui_quinn_network_peers{network=\"$network\", group=\"Fullnode\"}",
       "legendFormat": "Peers"
      }
     ]
    },
    {
     "title": "DB Pruning",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "avg_over_time(last_pruned_effects_checkpoint{network=\"$network\", group=\"Fullnode\"}[24h])",
       "legendFormat": "Last Pruned Checkpoint"
      }
     ]
    },
    {
     "title": "Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
     "targets": [
      {
       "expr": "highest_synced_checkpoint{network=\"$network\", group=\"Fullnode\"}",
       "legendFormat": "Highest Synced"
      },
      {
       "expr": "highest_known_checkpoint{network=\"$network\", group=\"Fullnode\"}",
       "legendFormat": "Highest Known"
      },
      {
       "expr": "highest_verified_checkpoint{network=\"$network\", group=\"Fullnode\"}",
       "legendFormat": "Highest Verified"
      },
      {
       "expr": "last_executed_checkpoint{network=\"$network\", group=\"Fullnode\"}",
       "legendFormat": "Last Executed"
      }
     ]
    },
    {
     "title": "Node Requests (/s) by Route [1 m avg]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "rate(sui_inbound_requests{network=\"$network\", group=\"Fullnode\"}[1m])",
       "legendFormat": "inbound - {{route}}"
      },
      {
       "expr": "rate(sui_outbound_requests{network=\"$network\", group=\"Fullnode\"}[1m])",
       "legendFormat": "outbound - {{route}}"
      }
     ]
    },
    {
     "title": "Incoming RPC Requests (/s) by Route [1 m avg]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "rate(rpc_requests_by_route{network=\"$network\", group=\"Fullnode\"}[1m])",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Avg Node Requests Latency by Route",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "1000\r\n*\r\n(\r\n  sui_outbound_request_latency_sum{network=\"$network\", group=\"Fullnode\"}\r\n  /\r\n  sui_outbound_request_latency_count{network=\"$network\", group=\"Fullnode\"}\r\n)",
       "legendFormat": "outbound - {{route}}"
      },
      {
       "expr": "1000\r\n*\r\n(\r\n  sui_inbound_request_latency_sum{network=\"$network\", group=\"Fullnode\"}\r\n  /\r\n  sui_inbound_request_latency_count{network=\"$network\", group=\"Fullnode\"}\r\n)",
       "legendFormat": "inbound - {{route}}"
      }
     ]
    },
    {
     "title": "Avg Spans Latency",
     "type": "timeseries",
     "description": "Displays the average latency for spans in the fullnode service.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(tracing_span_latencies_sum{group=\"Fullnode\", network=\"$network\"} / tracing_span_latencies_count{group=\"Fullnode\", network=\"$network\"}) / 1e9",
       "legendFormat": "{{span_name}}"
      }
     ]
    }
   ]
  }
 ]
}